version: 2
workflows:
  version: 2
  rspec:
    jobs:
      - build:
          context:
            - docker-hub-creds
jobs:
  build:
    docker:
      - image: ruby:2.6.5
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS

    steps:
      - checkout
      - run: bundle install -j4 --path vendor/bundle
      - run: bundle exec rspec
